#!/bin/bash



DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR"  ]]; then DIR="$PWD"; fi
source "$DIR/awk.sh"

usage() { 
    echo "Usage: $0 [<SR|LR>] [-p <pb-rs2|pb-sequel|ont-ligation|ont-rapid|ont-1dsq>] [-i <fq.gz>] [-o <outputDir>] [-m] [-q <qcoption>]" 1>&2 ;  
}
if [ -z $1 ];
then
    usage;
fi
READS=$1;
shift;
#path to call main.nf script outside its directory
path=$(dirname $0)
while getopts "p:i:o:mrq:h" o;
do
    case $o in
        p) PLATFORM=$OPTARG ;;
        i) INPUTS=$OPTARG ;;
        o) OUTPUTS=$OPTARG ;;
        m) MERGES=true ;;
        r) RESUME="-resume";;
        q) QCOPT=$OPTARG ;;
        h) HELPPPP ;;
    esac
done;
shift $((OPTIND - 1))


if [ -n "$READS" ]
then
    case $READS in
        SR) main_script=main.nf 
            filename="*{1,2}.fq.gz"
            run=true
            ;;
        LR) main_script=main-longread.nf 
            filename="*.fq.gz"
            run=true
            if [[ 'pb-rs2 pb-sequel ont-ligation ont-rapid ont-1dsq' =~ (^|[[:space:]])"$PLATFORM"($|[[:space:]]) ]]
            then
                platform="--platform='$PLATFORM'"
            else
                usage; 
                echo "Usage: must specify platform -p {pb-rs2, pb-sequel, ont-ligation, ont-rapid, ont-1dsq}"
                exit 65
            fi
            ;;
        QCsum) shift ;
            extract_fastqc $@ | column -t -s $'\t' ;;
        compare) calculate_percent $2 $3 $4 ;;
        *) echo "Usage : must specify reads type, SR - short read, LR - long read"
           exit 65 ;;
    esac
else
    echo "specify reads type, SR - short read, LR - long read" 
    exit 65 
fi;



if [ -n "$INPUTS" ]
then
    input="--input=$INPUTS/$filename"
else
    input="--input=$PWD/$filename"
fi



if [ -n "$OUTPUTS" ]
then 
    output="--results=$OUTPUT"
else
    output="--results=$PWD/results"
fi



if [ -n "$MERGES" ]
then 
    merge="--mergeUnpair=$MERGES"
else
    merge=''
fi



if [ -n "$QCOPT" ]
then 
    qcopt="$QCOPT"
elif [ "$READS" = "SR" ]
then

    qcopt="SLIDINGWINDOW:4:30 MINLEN:70"

elif [ "$READS" = "LR" ]
then
    qcopt="--min_length 10000 --keep_percent 90"
fi 

if [ $run ]
then
    echo "nextflow run $path/$main_script $platform $input $output $merge --qc_option=$qcopt" $RESUME
    nextflow run $path/$main_script $platform $input $output $merge --qc_option="$qcopt" $RESUME
fi
