#!/bin/bash

usage() { echo "Usage: $0 target-file" 1>&2 ; exit 1; }
if [ -z $1 ];
then
    usage;
fi



while getopts "r:p:i:o:mq:" o;
do
    case $o in
        r) READS=$OPTARG ;;
        p) PLATFORM=$OPTARG ;;
        i) INPUTS=$OPTARG ;;
        o) OUTPUTS=$OPTARG ;;
        m) MERGES=true ;;
        q) QCOPT=$OPTARG ;;

    esac
done;
shift $((OPTIND -1))



if [ -n "$READS" ]
then
    case $READS in
        SR) main_script=main.nf ;;
        LR) main_script=main-longread.nf 
            if [[ 'pb-rs2 pb-sequel ont-ligation ont-rapid ont-1dsq' =~ (^|[[:space:]])"$PLATFORM"($|[[:space:]]) ]]
            then
                platform="--params.platform=='$PLATFORM'"
            else
                echo "Usage: must specify platform -p {pb-rs2, pb-sequel, ont-ligation, ont-rapid, ont-1dsq}"
                exit 65
            fi
            ;;
        *) echo "Usage : specify reads type, SR - short read, LR - long read"
           exit 65 ;;
    esac
else
    echo "specify reads type, SR - short read, LR - long read" 
    exit 65 
fi;



if [ -n "$INPUTS" ]
then
    input="--params.input='$INPUTS'"
else
    input="--params.input='$PWD/*{1,2}.fq.gz'"
fi



if [ -n "$OUTPUTS" ]
then 
    output="--params.results='$OUTPUT'"
else
    output="--param.results='$PWD/results'"
fi



if [ -n "$MERGES" ]
then 
    merge="--mergeUnpair=$MERGES"
else
    merge=''
fi



if [ -n "$QCOPT" ]
then 
    qcopt="--params.qc_option=$QCOPT"
elif [ "$READS" = "SR" ]
then

    qcopt="--params.qc_option='SLIDINGWINDOW:4:30 MINLEN:70'"

elif [ "$READS" = "LR" ]
then
    qcopt="--params.qc_option='--min_length 10000 --keep_percent 90'"
fi 
echo "nextflow run $main_script $platform $input $output $merge $qcopt"
