#!/bin/bash

usage() { echo "Usage: $0 target-file" 1>&2 ; exit 1; }
if [ -z $1 ];
then
    usage;
fi

path=`dirname $0`

while getopts "r:p:i:o:mq:" o;
do
    case $o in
        r) READS=$OPTARG ;;
        p) PLATFORM=$OPTARG ;;
        i) INPUTS=$OPTARG ;;
        o) OUTPUTS=$OPTARG ;;
        m) MERGES=true ;;
        q) QCOPT=$OPTARG ;;

    esac
done;
shift $((OPTIND -1))



if [ -n "$READS" ]
then
    case $READS in
        SR) main_script=main.nf ;;
        LR) main_script=main-longread.nf 
            if [[ 'pb-rs2 pb-sequel ont-ligation ont-rapid ont-1dsq' =~ (^|[[:space:]])"$PLATFORM"($|[[:space:]]) ]]
            then
                platform="--platform='$PLATFORM'"
            else
                echo "Usage: must specify platform -p {pb-rs2, pb-sequel, ont-ligation, ont-rapid, ont-1dsq}"
                exit 65
            fi
            ;;
        *) echo "Usage : specify reads type, SR - short read, LR - long read"
           exit 65 ;;
    esac
else
    echo "specify reads type, SR - short read, LR - long read" 
    exit 65 
fi;



if [ -n "$INPUTS" ]
then
    input="--input=$INPUTS"
else
    input="--input=$PWD/*{1,2}.fq.gz"
fi



if [ -n "$OUTPUTS" ]
then 
    output="--results=$OUTPUT"
else
    output="--results=$PWD/results"
fi



if [ -n "$MERGES" ]
then 
    merge="--mergeUnpair=$MERGES"
else
    merge=''
fi



if [ -n "$QCOPT" ]
then 
    qcopt="$QCOPT"
elif [ "$READS" = "SR" ]
then

    qcopt="SLIDINGWINDOW:4:30 MINLEN:70"

elif [ "$READS" = "LR" ]
then
    qcopt="--min_length 10000 --keep_percent 90"
fi 

echo "nextflow run $path/$main_script $platform $input $output $merge $qcopt"
nextflow run $path/$main_script $platform $input $output $merge --qc_option="$qcopt"

